name: Test Use of Common Dev Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      install_command: "npm ci"
      cloud_deploy: false
      skip_deploy: true
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_LOCAL }}
      BUILD_ARGS: ''
      DOCKER_BUILD_ARGS: ''
