name: Test Use of Common Prod Workflow
on: workflow_dispatch
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-prod-common.yml@main
    with:
      needs_build: true
      install_command: "npm ci"
      cloud_deploy: false
      skip_deploy: false
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_PROD }}
      BUILD_ARGS: ''
      DOCKER_BUILD_ARGS: ''
